### ISSUE TITLE
Multi-tokens stop sequence

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#104]
I would like to use mistral.rs as a backend on https://github.com/lucasavila00/LmScript

LmScript hopes to hide the token concept from users so it needs support for multi-token stop sequences.

I can try implementing it, if it is a desired feature.

**Comment by EricLBuehler** [comment]
@lucasavila00, thanks for offering: this is certainly a desired feature! Most of the code to support this should already be in place, and if you could try to implement it, that would be great.
