### ISSUE TITLE
A binary/command to run on the profiler

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#118]
The server currently executes forever, and requires a call from an external program.

It would be nice if there were a binary (or command to be passed to the server) that makes it execute a prompt from CLI and exit after that.

To use both the Nvidia Visual Profiler and the Samply profiler I needed to edit the code to make the process exit after answering a single request, that I started with curl.

**Comment by EricLBuehler** [comment]
This has been implemented in #119.
