### ISSUE TITLE
Support different model sizes and variations

### ISSUE THREAD

**Issue by ivanbaldo** [EricLBuehler/mistral.rs#15]
Currently when running `mistralrs-server --port 8080 llama` it downloads `Llama-2-13b-chat-hf`, but it would be nice to be able to specify other sizes and maybe other fine tuned models that work the same and with the same template, etc.

**Comment by EricLBuehler** [comment]
This can be done by specifying the model with the -m flag. If you pass --help after the subcommand, then it will show all options.

**Comment by ivanbaldo** [comment]
Oh! Amazing! Didn't occur to me that there was sub-help for the commands!
Now that I look at the main help screen, it mentions it, my bad.

**Comment by EricLBuehler** [comment]
Glad to help!
