### ISSUE TITLE
Infra: Create mistralrs-bench

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#164]
I think it should be mostly a copy of https://github.com/ggerganov/llama.cpp/blob/master/examples/llama-bench/README.md

Makes it easy to compare the 2 projects

Our current `--prompt` setup is good enough for profiling but not for benchmarking.

Refs https://github.com/EricLBuehler/mistral.rs/pull/162#issuecomment-2060055590

**Comment by EricLBuehler** [comment]
Thanks for bringing this up. If you want to start this, that would be great although I can also implement it tomorrow.

**Comment by lucasavila00** [comment]
I'll start it.

**Comment by EricLBuehler** [comment]
Sounds good.
