### ISSUE TITLE
X-LoRA, nonquant models crash with OOM again

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/mistral.rs#165]
Strangely, this is happening again. @lucasavila00, can you please run your CPU memory leak checks to see if we are still leaking memory? I am very confused as it looked like this was fixed.

Refs https://github.com/huggingface/candle/issues/2079.

**Comment by lucasavila00** [comment]
I have to learn how to run lora, then xlora, to run it. I have never done it before.

BTW maybe it is the prefix cache? https://github.com/EricLBuehler/mistral.rs/issues/167
