### ISSUE TITLE
Prefix cache is not evicted before OOM

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#167]
I found it while working on mistralrs-bench.

I could only run concurrency=5, n=128 after disabling prefix cache fully in commit https://github.com/EricLBuehler/mistral.rs/pull/166/commits/c1efae080ccdac6bd7c0cc83a00f38ac50995a23

**Comment by EricLBuehler** [comment]
This problem may have been linked to the now-nonexistant bug in #165 because the prefix cache is only updated after the sequence is finished.
