### ISSUE TITLE
mistral-bench: Missing docs on how to run

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#172]

**Comment by EricLBuehler** [comment]
@lucasavila00, I've implemented and closed some of your issues regarding mistralrs-bench. Would you be able to write these docs?

**Comment by lucasavila00** [comment]
@EricLBuehler this is a busy week for me, but I'll try to do it this week

**Comment by EricLBuehler** [comment]
Great, thanks.
