### ISSUE TITLE
Linking error on Windows

### ISSUE THREAD

**Issue by siriux** [EricLBuehler/mistral.rs#181]
There is an error when building on windows. On the linking phase, I get this error: "note: LINK : fatal error LNK1181: cannot open input file 'layernorm.lib'"

The problem is that in the build.rs file below, the filename is only valid for linux, renaming the generated file to the expected one (from liblayernorm.a to layernorm.lib) seems to fix this issue (there are more issues left, but still checking if the problems are on my side).

https://github.com/EricLBuehler/candle-layer-norm/blob/4cebe4bafed612eb211d76092556d0a41fd6f1cc/build.rs#L54

**Comment by siriux** [comment]
The other error I get it's linking "stdc++.lib". 
I think we shouldn't link it on windows (this I didn't test it, but makes sense).

Here it's an example of how they are handling it on rusty_v8 build script:
https://github.com/denoland/rusty_v8/blob/20b2989186d1ecdf4c291d0706ff9eb1baaf2cfd/build.rs#L602

**Comment by EricLBuehler** [comment]
Thanks for reporting this. I've made that change with the `liblayernorm.a` file so it is more intelligent now. I think that the only usage of `stdc++` is when it is building flash attention kernels, so I've updated that code. Can you please try it again?

**Comment by EricLBuehler** [comment]
Ok, I've fixed those, and it should be more intelligent about linking to stdc++ on Windows now.

**Comment by siriux** [comment]
Thanks for the fixes, it's building on windows now.

**Comment by EricLBuehler** [comment]
Great!
