### ISSUE TITLE
Sliding window models do not properly slice KV cache

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/mistral.rs#246]
**Describe the bug**
This affects models which use sliding window attention, but only when the sequence length is great enough (seq_len > sliding_window) to need the sliding window. This will be fixed in #244.

**Latest commit**
[4505a5e](https://github.com/EricLBuehler/mistral.rs/commit/4505a5e4f5e53d924d3caa2f9182639e8967a7bb)

**Comment by LLukas22** [comment]
I guess this could also be realated to phi-3 producing gibberish output on long input sequences?

**Comment by EricLBuehler** [comment]
Yes, this is the reason.
