### ISSUE TITLE
Problem running with Mac M1

### ISSUE THREAD

**Issue by wking1986** [EricLBuehler/mistral.rs#252]
My mac has an m1 chip, execute the following command：
 cargo run --release --features mkl -- -i plain -m meta-llama/Meta-Llama-3-8B-Instruct -a llama

The following error occurs. Does it mean that the arm architecture is not supported?

= note: ld: warning: ignoring file /Users/wwz/anaconda3/lib/libpython3.10.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
          ld: warning: ignoring file /Users/wwz/anaconda3/lib/libc++.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
          ld: warning: ignoring file /Users/wwz/anaconda3/lib/libiconv.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
          Undefined symbols for architecture x86_64:

**Comment by EricLBuehler** [comment]
@wking1986 can you reproduce the issue without the `--features mkl`? MKL is Intel, so it seems like it is building for `x86_64`. Perhaps `--features accelerate` would be best?
