### ISSUE TITLE
Add C api and provide shared and static libraries.

### ISSUE THREAD

**Issue by maximus2600** [EricLBuehler/mistral.rs#258]
It would be nice to a stable (or versioned) C api and provide a way to compiled shared and static libraries so one can created bindings for various othe languages.

The advantage is one can use these to embed inference engine into their own programs to eliminate the network/http latencies, which might be crucial for low compute tasks when network latency is greater than the actual compute.

Other is that once there are bindings for various languages, a lot more people can write micro services/web GUI/..., which will broaden the usage of this project.

**Comment by EricLBuehler** [comment]
@maximus2600 no plans for this at the moment.
