### ISSUE TITLE
distribute with cargo dist?

### ISSUE THREAD

**Issue by ashleygwilliams** [EricLBuehler/mistral.rs#263]
love to see more rust in the AI space. i work on a tool called cargo-dist that can help package up pre-built binaries and build installers so it's easier for folks to get up and running with your project (without having to install rust or sys deps manually). let me know if you'd be interested at all, would be happy to work with you to get it set up! 

https://github.com/axodotdev/cargo-dist

**Comment by EricLBuehler** [comment]
Hi @ashleygwilliams! I think that this would be a great addition. I think an installer would work best here due to the wide variety of `--features` and also the Python API. If you could submit a PR adding this, it would be great!

**Comment by EricLBuehler** [comment]
Hello @ashleygwilliams! I am very interested in using cargo dist to improve ease of installation, have you made progress with this?
