### ISSUE TITLE
interactive mode should accept EOF

### ISSUE THREAD

**Issue by coder543** [EricLBuehler/mistral.rs#266]
**Describe the bug**

The interactive mode (`-i`) does not understand EOF. In interactive CLIs, `ctrl-d` is usually used to exit them, which emits an EOF into the stream. This just causes `mistral.rs` to go haywire. Similarly, a pipe will emit an EOF when it is done, which causes the same breakdown. For example:

```
$ echo "Some prompt here" | cargo run --release --features "cuda cudnn" -- -i --isq Q4K plain -m microsoft/Phi-3-mini-128k-instruct -a phi3
```

Once it receives the EOF, it just starts sending blank messages to the model every time the model finishes answering the previous blank message.

**Comment by EricLBuehler** [comment]
@coder543, thank you for reporting this. I have fixed it in #267, can you please confirm that the fix works?

**Comment by coder543** [comment]
Yep, I can confirm it is fixed! Thanks!

**Comment by EricLBuehler** [comment]
Great!
