### ISSUE TITLE
pip install of mistralrs not working

### ISSUE THREAD

**Issue by joshpopelka20** [EricLBuehler/mistral.rs#288]
**Describe the bug**
Trying to pip install mistralrs using Amazon Sagemaker (using Amazon Linux and Python 3.10). I have cargo and rust installed, and the cargo bin directory is on my PATH. This is the error message I get when I run the pip install:

>   × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]

**Latest commit**
7b3bb8d184749131da3a34ac90362bc2155156bf

**Comment by EricLBuehler** [comment]
Can you please run `which cargo` to verify where it is?

**Comment by joshpopelka20** [comment]
getting: ~/.cargo/bin/cargo

**Comment by EricLBuehler** [comment]
That is very strange. Did you install Cargo via the `rustup.rs` site? It works on my instance where I installed it with their installer: 
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by joshpopelka20** [comment]
yes, I started a new instance and retried Cargo install. I left all the defaults and still getting the same error.

![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/caa839c5-3cde-409a-a640-ac0a80a9bc41)

**Comment by EricLBuehler** [comment]
Ok. Can you try a build of the Rust side as per the readme (git clone, cargo build) and make sure that works?

**Comment by joshpopelka20** [comment]
I was able to build and pip install mistralrs. I'm trying it for cuda next.

**Comment by joshpopelka20** [comment]
Looks like there is an issue with building for cuda. I get this when I run `cargo build --release --features "cuda flash-attn"`


> # stdout
> 
> 
>   # stderr
> 
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>   #$ fatbinary -64 --cicc-cmdline="-ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 " "--image3=kind=elf,sm=86,file=/tmp/tmpxft_00002ee4_00000000-8_flash_fwd_hdim64_bf16_sm80.sm_86.cubin" "--image3=kind=ptx,sm=86,file=/tmp/tmpxft_00002ee4_00000000-6_flash_fwd_hdim64_bf16_sm80.ptx" --embedded-fatbin="/tmp/tmpxft_00002ee4_00000000-3_flash_fwd_hdim64_bf16_sm80.fatbin.c" 
>   #$ ptxas -arch=sm_86 -m64  "/tmp/tmpxft_00002f4d_00000000-6_flash_fwd_hdim96_bf16_sm80.ptx"  -o "/tmp/tmpxft_00002f4d_00000000-8_flash_fwd_hdim96_bf16_sm80.sm_86.cubin" 
>   #$ rm /tmp/tmpxft_00002ee4_00000000-3_flash_fwd_hdim64_bf16_sm80.fatbin
>   #$ gcc -std=c++17 -D__CUDA_ARCH__=860 -D__CUDA_ARCH_LIST__=860 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -O3 -I"cutlass/include" "-I/usr/local/cuda-12.1/bin/../targets/x86_64-linux/include"   -m64 "/tmp/tmpxft_00002ee4_00000000-6_flash_fwd_hdim64_bf16_sm80.cudafe1.cpp" -o "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim64_bf16_sm80-eaa7ce7f57eb7351.o" 
>   #$ ptxas -arch=sm_86 -m64  "/tmp/tmpxft_00002ae9_00000000-6_flash_fwd_hdim256_fp16_sm80.ptx"  -o "/tmp/tmpxft_00002ae9_00000000-8_flash_fwd_hdim256_fp16_sm80.sm_86.cubin" 
>   #$ fatbinary -64 --cicc-cmdline="-ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 " "--image3=kind=elf,sm=86,file=/tmp/tmpxft_00002f4d_00000000-8_flash_fwd_hdim96_bf16_sm80.sm_86.cubin" "--image3=kind=ptx,sm=86,file=/tmp/tmpxft_00002f4d_00000000-6_flash_fwd_hdim96_bf16_sm80.ptx" --embedded-fatbin="/tmp/tmpxft_00002f4d_00000000-3_flash_fwd_hdim96_bf16_sm80.fatbin.c" 
>   #$ rm /tmp/tmpxft_00002f4d_00000000-3_flash_fwd_hdim96_bf16_sm80.fatbin
>   #$ gcc -std=c++17 -D__CUDA_ARCH__=860 -D__CUDA_ARCH_LIST__=860 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -O3 -I"cutlass/include" "-I/usr/local/cuda-12.1/bin/../targets/x86_64-linux/include"   -m64 "/tmp/tmpxft_00002f4d_00000000-6_flash_fwd_hdim96_bf16_sm80.cudafe1.cpp" -o "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim96_bf16_sm80-f51ba409eb93ce41.o" 
>   #$ ptxas -arch=sm_86 -m64  "/tmp/tmpxft_00002e90_00000000-6_flash_fwd_hdim256_bf16_sm80.ptx"  -o "/tmp/tmpxft_00002e90_00000000-8_flash_fwd_hdim256_bf16_sm80.sm_86.cubin" 
>   #$ fatbinary -64 --cicc-cmdline="-ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 " "--image3=kind=elf,sm=86,file=/tmp/tmpxft_00002ae9_00000000-8_flash_fwd_hdim256_fp16_sm80.sm_86.cubin" "--image3=kind=ptx,sm=86,file=/tmp/tmpxft_00002ae9_00000000-6_flash_fwd_hdim256_fp16_sm80.ptx" --embedded-fatbin="/tmp/tmpxft_00002ae9_00000000-3_flash_fwd_hdim256_fp16_sm80.fatbin.c" 
>   #$ rm /tmp/tmpxft_00002ae9_00000000-3_flash_fwd_hdim256_fp16_sm80.fatbin
>   #$ gcc -std=c++17 -D__CUDA_ARCH__=860 -D__CUDA_ARCH_LIST__=860 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -O3 -I"cutlass/include" "-I/usr/local/cuda-12.1/bin/../targets/x86_64-linux/include"   -m64 "/tmp/tmpxft_00002ae9_00000000-6_flash_fwd_hdim256_fp16_sm80.cudafe1.cpp" -o "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim256_fp16_sm80-6bbb415157454ca9.o" 
>   #$ fatbinary -64 --cicc-cmdline="-ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 " "--image3=kind=elf,sm=86,file=/tmp/tmpxft_00002e90_00000000-8_flash_fwd_hdim256_bf16_sm80.sm_86.cubin" "--image3=kind=ptx,sm=86,file=/tmp/tmpxft_00002e90_00000000-6_flash_fwd_hdim256_bf16_sm80.ptx" --embedded-fatbin="/tmp/tmpxft_00002e90_00000000-3_flash_fwd_hdim256_bf16_sm80.fatbin.c" 
>   #$ rm /tmp/tmpxft_00002e90_00000000-3_flash_fwd_hdim256_bf16_sm80.fatbin
>   #$ gcc -std=c++17 -D__CUDA_ARCH__=860 -D__CUDA_ARCH_LIST__=860 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -O3 -I"cutlass/include" "-I/usr/local/cuda-12.1/bin/../targets/x86_64-linux/include"   -m64 "/tmp/tmpxft_00002e90_00000000-6_flash_fwd_hdim256_bf16_sm80.cudafe1.cpp" -o "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim256_bf16_sm80-21dd0f7dd998e506.o" 
> 
>

**Comment by joshpopelka20** [comment]
Sorry, I think this is the error:

>   #$ ptxas -arch=sm_86 -m64  "/tmp/tmpxft_00002e9b_00000000-6_flash_fwd_hdim32_bf16_sm80.ptx"  -o "/tmp/tmpxft_00002e9b_00000000-8_flash_fwd_hdim32_bf16_sm80.sm_86.cubin" 
>   #$ ptxas -arch=sm_86 -m64  "/tmp/tmpxft_00002ee4_00000000-6_flash_fwd_hdim64_bf16_sm80.ptx"  -o "/tmp/tmpxft_00002ee4_00000000-8_flash_fwd_hdim64_bf16_sm80.sm_86.cubin" 
>   nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)
>   # --error 0xb --
>   thread '<unnamed>' panicked at /home/ec2-user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:262:21:
>   nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_86" "-c" "-o" "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim32_bf16_sm80-aca7d8fdce93ef53.o" "--default-stream" "per-thread" "-std=c++17" "-O3" "-U__CUDA_NO_HALF_OPERATORS__" "-U__CUDA_NO_HALF_CONVERSIONS__" "-U__CUDA_NO_HALF2_OPERATORS__" "-U__CUDA_NO_BFLOAT16_CONVERSIONS__" "-Icutlass/include" "--expt-relaxed-constexpr" "--expt-extended-lambda" "--use_fast_math" "--verbose" "kernels/flash_fwd_hdim32_bf16_sm80.cu"

**Comment by EricLBuehler** [comment]
Ok, great that you were able to pip install! Can you please let me know the output of:
- `nvidia-smi`
- `nvcc --version`

**Comment by joshpopelka20** [comment]
nvidia-smi

![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/d45976d9-9a6a-4dd7-a7d4-77fde0981688)

nvcc --version

![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/85bccf7c-2adb-4b6f-a4ac-d0978d1d7209)

which nvcc

![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/d1801702-7294-49b1-9c25-93208f20128d)

**Comment by EricLBuehler** [comment]
Ok, can you please retry the build with NVCC_CCBIN set to whatever `which nvcc` outputs: `NVCC_CCBIN="..." cargo run ...`

**Comment by joshpopelka20** [comment]
I'm not sure I want to do `cargo run` because I want to use Python (I'm iterating through some files to run inference).

I tried with `NVCC_CCBIN="/usr/local/cuda-12.1/bin/nvcc" cargo build --release --features "cuda flash-attn"` and got the same error:

>  <command-line>:0:0: warning: "__CUDA_ARCH_LIST__" redefined
>   <command-line>:0:0: note: this is the location of the previous definition
>   #$ cicc --c++17 --gnu_version=70301 --display_error_number --orig_src_file_name "kernels/flash_fwd_hdim96_bf16_sm80.cu" --orig_src_path_name "/home/ec2-user/.cargo/git/checkouts/candle-c6a149c3b35a488f/405af8d/candle-flash-attn/kernels/flash_fwd_hdim96_bf16_sm80.cu" --allow_managed --extended-lambda --relaxed_constexpr   -arch compute_86 -m64 --no-version-ident -ftz=1 -prec_div=0 -prec_sqrt=0 -fmad=1 -fast-math --gen_div_approx_ftz --include_file_name "tmpxft_00003b1f_00000000-3_flash_fwd_hdim96_bf16_sm80.fatbin.c" -tused --module_id_file_name "/tmp/tmpxft_00003b1f_00000000-4_flash_fwd_hdim96_bf16_sm80.module_id" --gen_c_file_name "/tmp/tmpxft_00003b1f_00000000-6_flash_fwd_hdim96_bf16_sm80.cudafe1.c" --stub_file_name "/tmp/tmpxft_00003b1f_00000000-6_flash_fwd_hdim96_bf16_sm80.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_00003b1f_00000000-6_flash_fwd_hdim96_bf16_sm80.cudafe1.gpu"  "/tmp/tmpxft_00003b1f_00000000-7_flash_fwd_hdim96_bf16_sm80.cpp1.ii" -o "/tmp/tmpxft_00003b1f_00000000-6_flash_fwd_hdim96_bf16_sm80.ptx"
>   nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)
>   # --error 0xb --
>   thread '<unnamed>' panicked at /home/ec2-user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:262:21:
>   nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_86" "-c" "-o" "/home/ec2-user/mistral.rs/target/release/build/candle-flash-attn-d4e3bffc95604f92/out/flash_fwd_hdim32_bf16_sm80-aca7d8fdce93ef53.o" "--default-stream" "per-thread" "-std=c++17" "-O3" "-U__CUDA_NO_HALF_OPERATORS__" "-U__CUDA_NO_HALF_CONVERSIONS__" "-U__CUDA_NO_HALF2_OPERATORS__" "-U__CUDA_NO_BFLOAT16_CONVERSIONS__" "-Icutlass/include" "--expt-relaxed-constexpr" "--expt-extended-lambda" "--use_fast_math" "--verbose" "-allow-unsupported-compiler" "-ccbin" "/usr/local/cuda-12.1/bin/nvcc" "kernels/flash_fwd_hdim32_bf16_sm80.cu"

**Comment by EricLBuehler** [comment]
Looks like this is the primary error: nvcc error : 'ptxas' died due to signal 11 (Invalid memory reference)

It's so strange that this error is occuring: It compiles fine on my [Lambda Labs](https://cloud.lambdalabs.com/instances) A10 with compute cap=8.6. Maybe it is an error relating to multiple CUDA installations on that machine?

**Comment by joshpopelka20** [comment]
which version of cuda are you using? Mine is 12.1. I saw this on Nvidia developer forums:

> Sanity check: Make sure all your CUDA header files belong to the same CUDA version the tool chain belongs to. I am not sure what the exact dependency is, but I believe it has to do with the declaration of vector types and the like.
> 
> If the sanity check comes up clean, **a seg fault (signal 11, GPF) indicates an internal compiler bug**, and you would want to file a bug report via the reporting form linked from the registered CUDA developer website.

link is: https://forums.developer.nvidia.com/t/nvcc-keeps-dying-on-me/36234

**Comment by EricLBuehler** [comment]
Here's the information from my instance:
`nvidia-smi`:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                     On  | 00000000:07:00.0 Off |                    0 |
|  0%   26C    P8               9W / 150W |      4MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

`nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```

`which nvcc`:
```
/usr/bin/nvcc
```

Maybe the CUDA driver needs to be updated for your machine? However, the above is an A10 while yours is an A10G, so maybe that plays a role. I've never had to check on these instances, as it always worked.

**Comment by joshpopelka20** [comment]
I'm having trouble upgrading my cuda version. Maybe, there's something to the comment about the cuda header files (since we're using different versions). Any idea how I can update the files on my end (which ones and where are they located)?

**Comment by joshpopelka20gmail** [comment]
Doing more research, I think it's an issue with the flash-attn feature. I see that it uses your candle flash-attn; I'm wondering if that might need some changes. I have access to an A100 instance and I'll try it tomorrow. Hoping that instance has CUDA 12.2

**Comment by joshpopelka20** [comment]
I looked into the candle-flash-attn library and saw the same error when I ran `cargo test`. I updated kernels/flash_fwd_launch_template.h  with this code:
```
void run_mha_fwd_hdim32(Flash_fwd_params &params, cudaStream_t stream) {
    constexpr static int Headdim = 32;
    BOOL_SWITCH(params.p_dropout < 1.f, Is_dropout, [&] {
        BOOL_SWITCH(params.is_causal, Is_causal, [&] {            if constexpr(!Is_dropout) {
                run_flash_fwd<Flash_fwd_kernel_traits<Headdim, 128, 128, 4, false, false, T>, Is_dropout, Is_causal>(params, stream);            } else {
                run_flash_fwd<Flash_fwd_kernel_traits<Headdim, 128, 64, 4, false, false, T>, Is_dropout, Is_causal>(params, stream);
            }
        });
    });
}
```

That got me past the "nvcc error : 'ptxas' died due to signal 11 (Invalid memory reference)" error.

Now, I'm getting this error:
relocation R_X86_64_32 against `.nvFatBinSegment' can not be used when making a shared object; recompile with -fPIC

I tried to add compiler options to the flash-attn build.rs, but it didn't fix the issue:

    let builder = bindgen_cuda::Builder::default()
        .kernel_paths(kernels)
        .out_dir(build_dir.clone())
        .arg("-std=c++17")
        .arg("-O3")
        *****.arg("--compiler-options")
        .arg("-fPIC")*****
        .arg("-U__CUDA_NO_HALF_OPERATORS__")
        .arg("-U__CUDA_NO_HALF_CONVERSIONS__")
        .arg("-U__CUDA_NO_HALF2_OPERATORS__")
        .arg("-U__CUDA_NO_BFLOAT16_CONVERSIONS__")
        .arg("-Icutlass/include")
        .arg("--expt-relaxed-constexpr")
        .arg("--expt-extended-lambda")
        .arg("--use_fast_math")
        .arg("--verbose");

**Comment by EricLBuehler** [comment]
Did you add the same to the `candle-layer-norm` build script? That also builds some things. Setting `CUDA_NVCC_FLAGS` should take care of those linking issues, though: can you try a build with that flag set, and your fix to `kernels/flash_fwd_launch_template.h`.

**Comment by joshpopelka20** [comment]
Looks like I just needed to clear the cache with `cargo clean` (no need to change `candle-layer-norm`) After that, `CUDA_NVCC_FLAGS="-fPIE" cargo test` ran successfully.

Tomorrow, I'll create a PR under your candle repo. After you merge, I'll test the pip install of mistralrs with flash-attention.

**Comment by joshpopelka20** [comment]
Added a PR under EricLBuehler/candle (https://github.com/EricLBuehler/candle/pull/3) to fix the issue with the cuda header file. Looks like you already added the code for the nvcc flags.

**Comment by EricLBuehler** [comment]
I just merged the PR. Also, we don't provide a `mistralrs-cuda-flash-attn` as I thought it would be too long of a name. Is this something you would like to see though?

**Comment by joshpopelka20** [comment]
The naming is fine. I tried the pip install again and it didn't work. Afterward, I tried git clone and `CUDA_NVCC_FLAGS="-fPIE" cargo build --release --features "cuda flash-attn"`. It returned this error:

use of undeclared crate or module `tokio`
        --> mistralrs-pyo3/src/lib.rs:14:5

**Comment by joshpopelka20** [comment]
Sorry, the build was successful. It was after the build, that I ran `pip install -U mistralrs-cuda` and got that error.

**Comment by EricLBuehler** [comment]
Ok, so just to confirm: you did a manual build with the command you specified (which succeeded), and then when you did the pip install after it failed?

**Comment by joshpopelka20** [comment]
Yes, that's correct. I retried the pip install after the manual build and got the same error:

 >       error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
>         --> mistralrs-pyo3/src/lib.rs:14:5
>          |
>       14 | use tokio::sync::mpsc::channel;
>          |     ^^^^^ use of undeclared crate or module `tokio`

**Comment by joshpopelka20** [comment]
I tried to follow the instructions on the pypi site [mistralrs-cuda](https://pypi.org/project/mistralrs-cuda/); in particular, `maturin develop -r --features "cuda flash-attn"`, but it only built the mistralrs code. Does the repo need a separate pyproject.toml for mistralrs-cuda?

**Comment by joshpopelka20** [comment]
I think I figured out that issue. I just needed to be a little patient as I got the error on my local after running maturin develop. To fix the issue, I updated the root Cargo.toml to include the "full" tokio feature. I've added a PR for that issue as well [tokio issue](https://github.com/EricLBuehler/mistral.rs/pull/299). I think you'll need to build and deploy to Pypi to update the code there. Afterward, I'll retry the pip install of mistralrs-cuda

**Comment by joshpopelka20** [comment]
I retried the `pip install -U mistralrs-cuda` with version 0.1.5 and I got an error. The NVCC flag needs to be passed. Do you know how to do that?

Error message:
> relocation R_X86_64_32 against symbol `_ZN10layer_norm13ln_fwd_kernelINS_13Kernel_traitsIfffffjLj3072ELj1ELj1ELj4ELj16ENS_18Kernel_traits_baseILj3072EfffffjLj128EEEEELb1ELb1ELb1ELb1EEEvNS_9FwdParamsE' can not be used when making a shared object; **recompile with -fPIC**

**Comment by joshpopelka20** [comment]
I was able to get it running in the terminal with this command:

> CUDA_NVCC_FLAGS="-fPIE" pip install -U mistralrs-cuda

I'm still having an issue with getting it to install from a jupyter notebook though.

I installed cargo through the terminal and see it on my path. When I try, to install `mistralrs-cuda` in the jupyter notebook, I get this error:

>      Cargo, the Rust package manager, is not installed or is not on PATH.
>       This package requires Rust and Cargo to compile extensions. Install it through
>       the system's package manager or via https://rustup.rs/

I even tried to install cargo using python's request and subprocess libraries, but it doesn't work either.

This is the python code I tried:

> import requests
> import subprocess
> import os
> 
> # Make the HTTPS request
> response = requests.get('https://sh.rustup.rs')
> 
> # Check if the request was successful
> if response.status_code == 200:
>     # Run the shell script
>     subprocess.run(['sh', '-s', '--', '-y'], input=response.text, text=True)
>     env = os.environ.copy()
> 
>     # Add the directory containing cargo to the PATH
>     env['PATH'] += os.pathsep + os.path.expanduser("$HOME/.cargo/env")
>     # Source cargo
>     result = subprocess.run(['. "$HOME/.cargo/env"'], shell=True, env=env)
>     if result.returncode != 0:
>         print("Error occurred:")
>         print("Standard Output:", result.stdout.decode())
>         print("Standard Error:", result.stderr.decode())
>     else:
>         print("Success")
>         
> else:
>     print("Failed to retrieve the script.")

**Comment by joshpopelka20** [comment]
I finally got it to work in a Jupyter notebook. This is the code for installing cargo and rust using python:
```
import requests
import subprocess
import os

# Make the HTTPS request
response = requests.get('https://sh.rustup.rs')

# Check if the request was successful
if response.status_code == 200:
    # Run the shell script
    subprocess.run(['sh', '-s', '--', '-y'], input=response.text, text=True)

    # Source cargo
    result = subprocess.run(['. "$HOME/.cargo/env"'], shell=True)
    if result.returncode != 0:
        print("Error occurred:")
        print("Standard Output:", result.stdout.decode())
        print("Standard Error:", result.stderr.decode())
    else:
        print("Success")
        current_path = os.environ.get('PATH', '')

        # Append the Rust bin directory to the PATH
        rust_bin_path = os.path.expanduser("~/.cargo/bin")
        new_path = f"{rust_bin_path}:{current_path}"

        # Update the PATH environment variable
        os.environ['PATH'] = new_path

        !rustc --version
        
else:
    print("Failed to receive a successful response.")
```

And this code will install mistralrs-cuda:
```
env = os.environ.copy()
env["CUDA_NVCC_FLAGS"] = "-fPIE"
result = subprocess.run(['pip', 'install', 'mistralrs-cuda'], env=env)
```

Thank you so much for your help with this! I'll close the issue as complete.
