### ISSUE TITLE
Cancel AI Answer without program termination in --interactive mode

### ISSUE THREAD

**Issue by fohvok** [EricLBuehler/mistral.rs#294]
Often, the response generated by the LLM is lengthy or veers off in an unintended direction. It would be a useful feature to be able to cancel the generation of a response without losing the context of the current session, similar to how ctrl-c is implemented in llama.cpp. This would allow users to maintain the flow of the conversation without having to restart the program.

**Comment by EricLBuehler** [comment]
@fohvok, I just merged support for this feature in #301. Does this work?

**Comment by fohvok** [comment]
The cancelling and continuing part works as intended.
At least on Linux i can end the program with ctrl-d. But maybe when the user can input text again, it should also be possible to do it with ctrl-c.

The following, that it stops early when having pressed ctrlc before, should also be irrelevant then:
```
> hi
Hi there! How can I help you today?
> ^Cwhat is 5+5?
5 +
>
```

**Comment by EricLBuehler** [comment]
@fohvok, I think after #315 this should be correctly implemented. Does this work?

**Comment by fohvok** [comment]
Now i get the following error:
```
> test
thread 'main' panicked at mistralrs-server/src/interactive_mode.rs:45:10:
Failed to set CTRL-C handler for interactive mode: MultipleHandlers
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Maybe related to [this](https://docs.rs/ctrlc/latest/ctrlc/fn.set_handler.html#warning).

**Comment by EricLBuehler** [comment]
Ah, ok. I just merged a fix for that, can you please check it again?

**Comment by fohvok** [comment]
It works now. Thank you!
