### ISSUE TITLE
mistral does not support NVIDIA V100 (compute_cap <= 800)

### ISSUE THREAD

**Issue by thesues** [EricLBuehler/mistral.rs#305]
**Describe the bug**
it does not support some old hardware.

Can it just convert bfloat16 to float16 before loading model. just like vllm is doing?

**Comment by EricLBuehler** [comment]
Hi @thesues!

This is a problem with the way we compile our CUDA kernels. I'll try to see if we can modify the compilation process (likely with conditional compilation) to avoid this, but it will probably be difficult.

**Comment by EricLBuehler** [comment]
@thesues I would recommend converting the model before loading.
