### ISSUE TITLE
Add support for llm-chain

### ISSUE THREAD

**Issue by joshpopelka20** [EricLBuehler/mistral.rs#307]
Trying to use mistralrs with llamaindex, but it's still quite slow. For my use case, I'm trying to get performance in millisecs. With llamaindex, performance is not ideal.

I'm wondering if I can use mistralrs with [llm-chain](https://llm-chain.xyz/) (it's a Rust-based alternative to llamaindex). I'd be willing to do the work to get the two to work together, but I'm not sure where to start. Can you let me know how I can integrate the two?

**Comment by EricLBuehler** [comment]
That sounds like a great idea.

To implement, the integration, I would recommend looking at how to connect their [`Executor` trait](https://github.com/sobelio/llm-chain/blob/main/crates/llm-chain/src/traits.rs#L53) with our [`Pipeline` trait](https://github.com/EricLBuehler/mistral.rs/blob/21a4022eadd14454fe17cfe8edbeb9c3387766ed/mistralrs-core/src/pipeline/mod.rs#L274). Mistral.rs is designed around the [`Engine`](https://github.com/EricLBuehler/mistral.rs/blob/21a4022eadd14454fe17cfe8edbeb9c3387766ed/mistralrs-core/src/engine/mod.rs#L38), which does the overseeing work of processing, scheduling, and running the `Pipeline`.

Currently, we don't have an embedding API, which we should probably add to implement this. I'm not very familiar with `llm-chain` so I'm not sure if that is a necessity. If it is, I'll try to add that API, as it has already been on my to-do list for some time.

**Comment by joshpopelka20** [comment]
Thanks for the info.

I'm going to close this for now as I've got another project I'll be working on for the next few weeks. If I have the time afterward, I'll reopen the issue and work on the solution.
