### ISSUE TITLE
Python mistralrs-cuda not running on GPU

### ISSUE THREAD

**Issue by joshpopelka20** [EricLBuehler/mistral.rs#342]
**Describe the bug**
After installing mistralrs-cuda, I tried to run inference using the below two steps (following the python API):

```
llm = Runner(
    which=Which.GGUF(
        tok_model_id="NousResearch/Meta-Llama-3-8B-Instruct",
        quantized_model_id="NousResearch/Meta-Llama-3-8B-Instruct-GGUF",
        quantized_filename="Meta-Llama-3-8B-Instruct-Q4_K_M.gguf",
        tokenizer_json=None,
        repeat_last_n=64,
    ),
    no_kv_cache=False,
    token_source=access_token,
    speculative_gamma=64,
    num_device_layers=32,
)
```

And:
```
output = llm.send_chat_completion_request(
    ChatCompletionRequest(
        model="llama",
        messages=messages,
        max_tokens=256,
        presence_penalty=1.0,
        top_p=0.1,
        temperature=0,
    )
)
```

Using nvidia-smi, I see no processes running
![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/fccfbce8-2fab-458e-beab-9052016a481e)

Running the model using rust seems to run on GPU `CUDA_NVCC_FLAGS="-fPIE" cargo run --release --features "cuda flash-attn cudnn" -- --token-source "literal:hf_.." -i plain -m meta-llama/Meta-Llama-3-8B-Instruct -a llama`
![image](https://github.com/EricLBuehler/mistral.rs/assets/107133849/cdafe7fe-1a6c-428a-a5bb-179803aaff46)

How do I get the python api to use CUDA?

**Latest commit**
5c3e9f1

**Comment by joshpopelka20** [comment]
I think this is more of an issue with the Sagemaker notebook I'm using. I'll leave the issue open for now, just in case it is an issue with the project.

**Comment by joshpopelka20** [comment]
Sorry, stupid mistake on my part. Closing the issue

**Comment by EricLBuehler** [comment]
Ah, ok. I was a bit worried the CUDA distribution was wrong, glad to hear that.
