### ISSUE TITLE
Speed in --interactive mode

### ISSUE THREAD

**Issue by fohvok** [EricLBuehler/mistral.rs#365]
The longer the conversation, the more noticeably is the speed decrease. I guess this is because on every new input the whole conversation gets send again. Is it maybe (easily) possible, that the state is "cached" and then just continues?

**Comment by EricLBuehler** [comment]
Hi @fohvok!

Yes, you are absolutely correct. The technique for this is to do prefix caching, but we are a bit limited there right now. I'm working on improving it in #350, and it should make interactive mode or really everything much faster.
