### ISSUE TITLE
Feature Req: Add Importance Matrix / RAM avail calculations to ISQ

### ISSUE THREAD

**Issue by psyv282j9d** [EricLBuehler/mistral.rs#377]
Looking over ISQ (based on your previous ask), I found a few things missing that I've learned are helpful via trial and error.  

`imatrix`, If you look at the discussion [here](https://github.com/ggerganov/llama.cpp/discussions/5263), you can see that calculating the Importance Matrix prior to quantization, can be used to offset some of the negative effects of quantization.  In particular, this [comment](https://github.com/ggerganov/llama.cpp/discussions/5263#discussioncomment-9437698) gives a great walkthrough of which tools to use to calculate the imatrix, then how to use it when quantizing. 

Also, one of the key benefits of Ollama (Go wrapper around llama.cpp) is in [`llm/memory.go`](https://github.com/ollama/ollama/blob/89d99001523bcf81f448973382cc7f6b9a68c578/llm/memory.go).  In the function `EstimateGPULayers`, it calculates, based on available VRAM (or system RAM for metal) how many layers can be offloaded to the GPU.  This number is then passed to the `--n_gpu_layers` option of `llama.cpp`.  

What are the chances of incorporating these ideas into ISQ?  It would be *great* to go from safetensors / `bf16` on disk to automagically optimal memory loading for inference. :-)

**Comment by psyv282j9d** [comment]
Oops.  I should add the `imatrix` calculation requires a data file.  The outcome of the previously referenced discussion seems to have settled on the file linked in this [comment](https://github.com/ggerganov/llama.cpp/discussions/5263#discussioncomment-9552049).

Direct link to [`group_merged-enhancedV3.txt](https://github.com/ggerganov/llama.cpp/files/15440637/groups_merged-enhancedV3.txt)

**Comment by EricLBuehler** [comment]
Hello @psyv282j9d!

This sounds like a great feature which I would love to add. I have begun work on tracking memory usage in #392. I will look into applying the imatrix quants, from what I understand it is a different quantization standard?

**Comment by psyv282j9d** [comment]
My understanding (IANAMLE), is that it calculates a matrix of weights, which adjusts the quantized values of "important" tensors. This leads to a quantized model that more closely mimics the original. 

From the [PR](https://github.com/ggerganov/llama.cpp/pull/4861):
> We can then use these <a_i^2> as importances (weights) in a weighted RMSE minimization when quantizing the tensor.

So, not a different quantization method, just really helpful tweak on top of the existing gguf quant methods.

(All errors my own :-))

**Comment by EricLBuehler** [comment]
@psyv282j9d I just added importance matrix calculations (see the [docs](https://github.com/EricLBuehler/mistral.rs/blob/master/docs/IMATRIX.md))! Closing this now, please feel free to reopen!
