### ISSUE TITLE
Crashing when trying to run with error "A command encoder is already encoding to this command buffer" on Metal

### ISSUE THREAD

**Issue by Luddo183** [EricLBuehler/mistral.rs#393]
**Describe the bug**
When I run mistral.rs with the command `cargo run --release --features metal -- -i plain -m microsoft/Phi-3-mini-128k-instruct -a phi3`, it suddenly crashes with the following error: 

`[AGXG13GFamilyCommandBuffer tryCoalescingPreviousComputeCommandEncoderWithConfig:nextEncoderClass:]:1015: failed assertion 'A command encoder is already encoding to this command buffer'`

Running the command with the `--features metal` flag removed seems to run fine, albeit slowly.

**Latest commit**
Built from commit 29fa2cb

**Comment by EricLBuehler** [comment]
@Luddo183 I just merged a fix, can you please confirm that it works?

**Comment by Luddo183** [comment]
Latest commits on master fixed the issue. It now runs on my M1.

**Comment by EricLBuehler** [comment]
Great!
