### ISSUE TITLE
Support loading tokenizer from `sentencepiece` model

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/mistral.rs#407]
Currently, if a sentencepiece `.model` file is provided, the user must run a provided script to convert into the equivalent `tokenizer.json`. By supporting `sentencepiece` models directly, we can avoid this requirement.

Note: This requires creating a `TokenizerLike` trait and abstracting the tokenizer source file loading process, which is already complicated given the need to support loading from GGUF tokenizers.

Potential crate: https://docs.rs/sentencepiece/latest/sentencepiece/

**Comment by polarathene** [comment]
> the user must run a provided script to convert into the equivalent `tokenizer.json`

Something that isn't very straight-forward apparently from upstream advice? 🤔 

An alternative option is deferring to a converter if you can reliably convert `tokenizer.model` to `tokenizer.json`?

I find the python tools a bit difficult to follow when I've looked at source of some of them.

---

> which is already complicated given the need to support loading from GGUF tokenizers.

Is it not able to leverage that? I thought I had read that Unigram was effectively SentencePiece? If the configuration can be mapped to the `tokenizers`  logic we already have then all we need is the data from `tokenizers.model` to fit into `PropsGGUF`?

**Comment by polarathene** [comment]
FWIW [here is `exllamav2` approach for `SentencePiece` support](https://github.com/turboderp/exllamav2/blob/master/exllamav2/tokenizer/spm.py) via a wrapper of their own that seems to match HF tokenizers API? (_both extend from [this common tokenizer class](https://github.com/turboderp/exllamav2/blob/master/exllamav2/tokenizer/tokenizer.py)_).

**Comment by EricLBuehler** [comment]
I think that this could be an interesting feature, but as you said, I also haven't received any issues about this. It is probably not critical, and we have other things to work on.

> I find the python tools a bit difficult to follow when I've looked at source of some of them.

Would you be able to tell me which ones? I would like to improve their quality.

**Comment by polarathene** [comment]
> Would you be able to tell me which ones?

It was early on into learning about LLMs, so it may have just been unfamiliarity and my lack of Python skills.

I think it was the `llama.cpp` python script for converting/quantizing to GGUF, and the same for EXL2.

There was also the one referenced in candle repo for converting `tokenizer.model` to `tokenizer.json`, one of the issues involved you and a maintainer there IIRC stating that a lib would be a bit tricky, but a rust CLI tool was doable in their opinion? They also said that that sort of conversion wasn't easy to give instructions for. I don't recall the linked source being that well documented either, so assume you had to read through the source.

I had not tried any of them locally, perhaps they gave decent CLI help output 🤷‍♂️ I was partially interested in the logic itself for writing a converter tool in rust.

**Comment by EricLBuehler** [comment]
Ok, great. I think the script right now is fine, but we should consider support for loading directly from sentencepiece as a longer-term goal.
