### ISSUE TITLE
Is there any plans to support AWQ and GPTQ in the future?

### ISSUE THREAD

**Issue by franklucky001** [EricLBuehler/mistral.rs#418]
support quantization of awq and gptq

**Comment by EricLBuehler** [comment]
Hi @franklucky001! I do plan on supporting other quantization method such as AWQ and GPTQ in the future. I would probably start with GPTQ.

**Comment by EricLBuehler** [comment]
@franklucky001 we are going to merge GPTQ soon!

**Comment by EricLBuehler** [comment]
@franklucky001 GPTQ and Marlin support have been merged already.

**Comment by BuildBackBuehler** [comment]
So does AWQ work? For some reason I could've sworn it was a form of GPTQ so I figure there's a possibility. Wish I had an AWQ model downloaded to try
