### ISSUE TITLE
adding a system prompt gets an error

### ISSUE THREAD

**Issue by ggilley** [EricLBuehler/mistral.rs#45]
I tried adding a system prompt with the default chat_template. I looks like it should support having a system prompt, but it seems like there is a logic error:

```
invalid operation: Conversation roles must alternate user/assistant/user/assistant/... (in chat_template:1)
```
When I look in the code it's this part that seems to be off when a system prompt is supplied.

```
if (message['role'] == 'user') != (loop.index0 % 2 == 0)
```

**Comment by EricLBuehler** [comment]
Could you please provide the model you are using? Some models [do not support system templates](https://github.com/vllm-project/vllm/issues/2080), and that error is intentional.

**Comment by ggilley** [comment]
Sorry, it was the mistral model:

`$ mistralrs-server --port 1234 --log output.log mistral`

**Comment by EricLBuehler** [comment]
The Mistral Instruct model is one of the models that do not support a system prompt, so the chat template disallows that. Perhaps you could prepend the system prompt text to the user message?

**Comment by ggilley** [comment]
Oh, thanks. Sorry for the noise and thanks for taking the time!

**Comment by EricLBuehler** [comment]
No problem!

**Comment by Jayantverma2** [comment]
there is one way to do that 
in tokenizer_config.json

in **chat template key**- 
put
"{% if messages[0]['role'] == 'system' %}{% set contains_sys_prompt = 1 %}{% else %}{% set contains_sys_prompt = 0 %}{% endif %}{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != ((loop.index0 + contains_sys_prompt) % 2 == 0) %}{{ raise_exception('Conversation roles must alternate (system/)user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'system' %}{{ '[INST] <<SYS>>' + message['content'].strip() + '<</SYS>>' }}{% elif message['role'] == 'user' %}{{ (' ' if contains_sys_prompt == 1 and loop.index0 == 1 else '[INST] ') + message['content'].strip() + ' [/INST] ' }}{% elif message['role'] == 'assistant' %}{{ message['content'].strip() + eos_token}}{% else %}{{ raise_exception('Only system, user and assistant roles are supported!') }}{% endif %}{% endfor %}"

by doing this u will be able to use system prompt and this follows mistral instructions
![Screenshot from 2024-04-18 16-22-44](https://github.com/EricLBuehler/mistral.rs/assets/158451133/b3ac0854-f246-470e-ac13-31e2de659d43)

**Comment by EricLBuehler** [comment]
Recently, there was an even easier way added: you can pass in a custom chat template. Here is the doc:
```bash
 -c, --chat-template <CHAT_TEMPLATE>
          JINJA chat template with `messages`, `add_generation_prompt`, `bos_token`, `eos_token`, and `unk_token` as inputs. Used if the automatic deserialization fails. If this ends with `.json` (ie., it is a file) then that template is loaded
```

From [this section](https://github.com/EricLBuehler/mistral.rs?tab=readme-ov-file#run).

For example, you can make a custom chat template file (saved as a JSON), which looks like this:
```json
{
    "chat_template": "..."
}
```

And then run:

`./mistralrs-server --port 1234 --log output.txt --chat-template <FILENAME HERE> mistral`

We provide the ChatML template and the HF default [here](https://github.com/EricLBuehler/mistral.rs/tree/master/chat_templates).  Hopefully this helps!
