### ISSUE TITLE
Compilation failure with `--features flash-attn`

### ISSUE THREAD

**Issue by n8henrie** [EricLBuehler/mistral.rs#485]
**Describe the bug**

I'm unable to compile with `--features flash-attn` for use with my 1080Ti (on an x86_64 arch linux host).

```console
$ nvidia-smi --query-gpu=compute_cap --format=csv,noheader
6.1
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```

I thought the candle team had resolved issues with my GPU after this: https://github.com/huggingface/candle/issues/353#issuecomment-1674941824

```console
$ cargo build --release --features "flash-attn"
...
```

The error is quite long: https://gist.github.com/n8henrie/eb013f86807fa3281edfdee766746673

**Latest commit**
Which commit you ran with.

```
$ git rev-parse HEAD
3a7913766b64432c34daa842017f0b2fbf765fed
```

**Comment by b0xtch** [comment]
Yup, I believe the consensus is there is something upstream to the Flash attention repo. The problem persists for cuda > `v12.x`

candle
- https://github.com/huggingface/candle/issues/1936

flash attention v2
- https://github.com/Dao-AILab/flash-attention/issues/1004

**Comment by EricLBuehler** [comment]
@b0xtch did you find any resolution?

**Comment by b0xtch** [comment]
> @b0xtch did you find any resolution?

Unfortunately not, I can't pinpoint the exact problem. Not sure who to ping

**Comment by n8henrie** [comment]
Confirming that `cargo build --release --features "flash-attn"` builds without error on 20b8204199b9c673d0faa7d662afb2d79bef294c with the same GPU as above

Arch linux

```
$ nvidia-smi --query-gpu=compute_cap --format=csv,noheader
6.1
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Oct_29_23:50:19_PDT_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0
```

**Comment by EricLBuehler** [comment]
Glad that it works!
