### ISSUE TITLE
Need parallel linears

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/mistral.rs#50]
- [ ] RowParallelLinear
- [ ] MergedColumnParallelLinear
- [ ] QKVParallelLinear

**Comment by hugoabonizio** [comment]
Is the plan to implement tensor sharding for both quantized and non-quantized versions?

**Comment by EricLBuehler** [comment]
Yes, that is the plan.

**Comment by hugoabonizio** [comment]
I'm quite interested in the parallelization in CUDA of the quantized models!

**Comment by EricLBuehler** [comment]
Yes! We are beginning work on this topic now.
