### ISSUE TITLE
Examples on Metal use CPU - no GPU - and produce no output...or take minutes  to execute --> MacOS M1 Max 64Gb

### ISSUE THREAD

**Issue by oddpxl** [EricLBuehler/mistral.rs#505]
**Describe the bug**

High CPU use - no GPU use - MacOS 14.4.1 - Macbookpro M1 Max 64Gb

cargo build --example phi3v --release --features metal
It takes minutes to execute the phiv3 on a small image - but I do get text output eventually.

or

cargo build --example gguf-locally --release --features metal

Output:
general.architecture: llama
general.file_type: 17
general.name: mistralai_mistral-7b-instruct-v0.1
general.quantization_version: 2
llama.attention.head_count: 32
llama.attention.head_count_kv: 8
llama.attention.layer_norm_rms_epsilon: 0.00001
llama.block_count: 32
llama.context_length: 32768
llama.embedding_length: 4096
llama.feed_forward_length: 14336
llama.rope.dimension_count: 128
llama.rope.freq_base: 10000

No output - just seems to keep crunching...   ..killed it after 25min lol

**Latest commit**
v0.1.24

**Comment by EricLBuehler** [comment]
@oddpxl thank you for reporting this. I just created #507 which correctly handles the device for the examples on metal. Can you please try it again after `git switch` to that branch?

**Comment by oddpxl** [comment]
Hey very happy to see mistral.rs - thanks Eric :)

I'm new to git so just to check...I did the following:

Deleted mistral.rs
git clone https://github.com/EricLBuehler/mistral.rs.git
git switch best_device_in_examples
cargo build --example phi3v --release --features metal

The result when running ./phi3v...

Error: Metal error matmul doesn't support BF16

Just give me a shout if you want me to try something else !

**Comment by EricLBuehler** [comment]
Thank you for running that, but I just opened #509. Can you please run:
```
git switch master
git pull
git switch metal_bf16_dtype
```
And then rerun the example?

**Comment by oddpxl** [comment]
Results:

./gguf_locally

general.architecture: llama
general.file_type: 17
general.name: mistralai_mistral-7b-instruct-v0.1
general.quantization_version: 2
llama.attention.head_count: 32
llama.attention.head_count_kv: 8
llama.attention.layer_norm_rms_epsilon: 0.00001
llama.block_count: 32
llama.context_length: 32768
llama.embedding_length: 4096
llama.feed_forward_length: 14336
llama.rope.dimension_count: 128
llama.rope.freq_base: 10000
Text: fit3207! AMA!
User 0: How do you have the username fit3207 on reddit without $fit3207
User 1: That's just how Reddit works. It's the way users create their usernames here so it doesn't contain dollar signs.
User 0: Hmm thanks!
User 2: Wait are you trying to make a reddit account and cant?
User 0: Yeah. It says that I can't use a d in my UID.
User 2: Just try using letters and digits specifically no special characters. If you want to use special characters, you have to use middle marks. For example, $fit3207 would be $fit3_207 orťfit3207----------------------------------------------"($#"fit3207"#...-", etc.

Time taken: 7.34s seconds ( seems very long to me )

----

./phi3v

Error: Metal contiguous to_dtype F64 F32 not implemented

**Comment by EricLBuehler** [comment]
I just merged #509, so if you could `git switch master` and then `git pull` that would be great.

> Error: Metal contiguous to_dtype F64 F32 not implemented

Can you please rerun with RUST_BACKTRACE=1 and paste the output?

> Not entirely fair comparison as I do not know how to set context and seed with mistral.rs - would like to find out ;)

Not sure what you mean with the seed? We have [mistralrs-bench](https://github.com/EricLBuehler/mistral.rs/tree/master/mistralrs-bench) for structured benchmarking, though.

Just to confirm, are you counting the total time that mistral.rs takes to run? I just opened #510 which changes the messages for the instruct models and displays the T/s count, can you please `git switch examples_chat` and try the GGUF example out again?

**Comment by oddpxl** [comment]
I'm new to Rust so let me know if I'm doing this wrong...

bash -c "RUST_BACKTRACE=1 cargo run --example phi3v --release --features metal"

Error: Metal contiguous to_dtype F64 F32 not implemented
   0: std::backtrace::Backtrace::create
   1: candle_core::error::Error::bt
   2: <candle_core::metal_backend::MetalStorage as candle_core::backend::BackendStorage>::to_dtype
   3: candle_core::tensor::Tensor::to_dtype
   4: mistralrs_core::layers::PhiRotaryEmbedding::new
   5: mistralrs_core::vision_models::phi3::Model::new
   6: <mistralrs_core::pipeline::vision_loaders::Phi3VLoader as mistralrs_core::pipeline::vision_loaders::VisionModelLoader>::load
   7: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_path
   8: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_hf
   9: phi3v::main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: std::rt::lang_start::{{closure}}
  12: std::rt::lang_start_internal
  13: _main


Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: <mistralrs_core::pipeline::vision_loaders::Phi3VLoader as mistralrs_core::pipeline::vision_loaders::VisionModelLoader>::load
   3: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_path
   4: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_hf
   5: phi3v::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: std::rt::lang_start_internal
   9: _main

**Comment by EricLBuehler** [comment]
That's what I need, thank you. I'll patch that soon, looks like it's coming from the PhiRotaryEmbedding

**Comment by oddpxl** [comment]
Also...

general.architecture: llama
general.file_type: 17
general.name: mistralai_mistral-7b-instruct-v0.1
general.quantization_version: 2
llama.attention.head_count: 32
llama.attention.head_count_kv: 8
llama.attention.layer_norm_rms_epsilon: 0.00001
llama.block_count: 32
llama.context_length: 32768
llama.embedding_length: 4096
llama.feed_forward_length: 14336
llama.rope.dimension_count: 128
llama.rope.freq_base: 10000

---> Text: Hello! How can I brighten up your day today?, Prompt T/s: 33.175358, Completion T/s: 31.94103

Much better !

**Comment by oddpxl** [comment]
Ah great - definitely have to try [https://github.com/EricLBuehler/mistral.rs/tree/master/mistralrs-bench](Mistral bench)

Seed can be specified with llama.cpp to make sure you get exactly the same run with a model...that obviously also requires same sampling chain and values etc ..how much difference it makes...is another matter :)

**Comment by EricLBuehler** [comment]
I see. I'll add some infrastructure for setting the seed, that would be a great addition.

**Comment by EricLBuehler** [comment]
> I'm new to Rust so let me know if I'm doing this wrong...
> 
> bash -c "RUST_BACKTRACE=1 cargo run --example phi3v --release --features metal"
> 
> Error: Metal contiguous to_dtype F64 F32 not implemented 0: std::backtrace::Backtrace::create 1: candle_core::error::Error::bt 2: <candle_core::metal_backend::MetalStorage as candle_core::backend::BackendStorage>::to_dtype 3: candle_core::tensor::Tensor::to_dtype 4: mistralrs_core::layers::PhiRotaryEmbedding::new 5: mistralrs_core::vision_models::phi3::Model::new 6: <mistralrs_core::pipeline::vision_loaders::Phi3VLoader as mistralrs_core::pipeline::vision_loaders::VisionModelLoader>::load 7: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_path 8: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_hf 9: phi3v::main 10: std::sys_common::backtrace::__rust_begin_short_backtrace 11: std::rt::lang_start::{{closure}} 12: std::rt::lang_start_internal 13: _main
> 
> Stack backtrace: 0: std::backtrace::Backtrace::create 1: anyhow::error::<impl core::convert::From for anyhow::Error>::from 2: <mistralrs_core::pipeline::vision_loaders::Phi3VLoader as mistralrs_core::pipeline::vision_loaders::VisionModelLoader>::load 3: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_path 4: <mistralrs_core::pipeline::vision::VisionLoader as mistralrs_core::pipeline::Loader>::load_model_from_hf 5: phi3v::main 6: std::sys_common::backtrace::__rust_begin_short_backtrace 7: std::rt::lang_start::{{closure}} 8: std::rt::lang_start_internal 9: _main

I just opened #512 which avoids the f64->f32 cast, can you please run
```
git switch master
git pull
git switch phi_rope_dtype
```
And then try the Phi3-V example again?

**Comment by EricLBuehler** [comment]
@oddpxl I just merged #512, I think it should work now!

**Comment by oddpxl** [comment]
git switch master --force
git pull
cargo run --example phi3v --release --features metal

thread 'main' panicked at mistralrs/examples/phi3v/main.rs:85:14:
internal error: entered unreachable code

---> bash -c "RUST_BACKTRACE=full cargo run --example phi3v --release --features metal"

thread 'main' panicked at mistralrs/examples/phi3v/main.rs:85:14:
internal error: entered unreachable code
stack backtrace:
   0:        0x105206e54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x105228c1c - core::fmt::write::heedef092c8c0962e
   2:        0x105203640 - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x105206cac - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x105207e08 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x105207afc - std::panicking::default_hook::h24535936bc1f51de
   6:        0x1052086c0 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   7:        0x1052080c4 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   8:        0x1052072dc - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
   9:        0x105207e60 - _rust_begin_unwind
  10:        0x1052642c0 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  11:        0x105264340 - core::panicking::panic::h65d5df1c072e7907
  12:        0x104b2231c - phi3v::main::hf464c9c427e37e17
  13:        0x104b18144 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4906dbbbb712181d
  14:        0x104b1a7d4 - std::rt::lang_start::{{closure}}::h713917c6c67c6294
  15:        0x1051fd3b4 - std::rt::lang_start_internal::hecc68fef83c8f44d
  16:        0x104b225a4 - _main

**Comment by EricLBuehler** [comment]
Hmm, `cargo run --example phi3v --release --features cuda` works. I just merged a PR to show information about the errors, can you please run `git pull` (assuming you are still on master) and retry?

**Comment by oddpxl** [comment]
Sure !

Result...

thread 'main' panicked at mistralrs/examples/phi3v/main.rs:87:39:
Model error: Metal error no metal implementation for bitwise. Response: Text: , Prompt T/s: inf, Completion T/s: NaN
stack backtrace:
   0:        0x104ca2e54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
   1:        0x104cc4c1c - core::fmt::write::heedef092c8c0962e
   2:        0x104c9f640 - std::io::Write::write_fmt::h7178e8e2ea928914
   3:        0x104ca2cac - std::sys_common::backtrace::print::h417292deb95532ed
   4:        0x104ca3e08 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
   5:        0x104ca3afc - std::panicking::default_hook::h24535936bc1f51de
   6:        0x104ca46c0 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
   7:        0x104ca40f0 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
   8:        0x104ca32dc - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
   9:        0x104ca3e60 - _rust_begin_unwind
  10:        0x104d002c0 - core::panicking::panic_fmt::hc2b459a5bd3dce66
  11:        0x1045bc9bc - phi3v::main::hf464c9c427e37e17
  12:        0x1045b3f84 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4906dbbbb712181d
  13:        0x1045b6614 - std::rt::lang_start::{{closure}}::h713917c6c67c6294
  14:        0x104c993b4 - std::rt::lang_start_internal::hecc68fef83c8f44d
  15:        0x1045bcdb0 - _main

**Comment by EricLBuehler** [comment]
Hi @oddpxl, I just opened #518 which should fix this. Can you please run:
```
git pull
git switch nonzero_handle_metal
```
And try it again?

**Comment by oddpxl** [comment]
Yay ! Success

Text: The image provided is mostly obscured with a large black area where detail would typically be present. However, a small white rectangular shape is visible in the upper left corner. Without more context or additional visible elements, it's not possible to provide a detailed analysis of the scene. The OCR text does not offer additional information relevant to the image content.<|end|>

---> Prompt T/s: 163.25008, Completion T/s: 6.6006603

Not sure if  the T/s is as expected ?

**Comment by EricLBuehler** [comment]
@oddpxl closing this... see #555.
