### ISSUE TITLE
/usr/bin/ld: cannot find -lstdc++: No such file or directory

### ISSUE THREAD

**Issue by fahdmirza** [EricLBuehler/mistral.rs#553]
Hi,
 I am trying to install mistral.rs on Ubuntu 22.04 and got following error:

Ubuntu@0136-ict-prxmx50056:~/mistral.rs$ cargo build --release --features cuda
   Compiling mistralrs-pyo3 v0.1.26 (/home/Ubuntu/mistral.rs/mistralrs-pyo3)
   Compiling mistralrs-bench v0.1.26 (/home/Ubuntu/mistral.rs/mistralrs-bench)
   Compiling mistralrs-server v0.1.26 (/home/Ubuntu/mistral.rs/mistralrs-server)
error: linking with `cc` failed: exit status: 1
  = note: /usr/bin/ld: cannot find -lstdc++: No such file or directory
          /usr/bin/ld: cannot find -lstdc++: No such file or directory
          collect2: error: ld returned 1 exit status

=============

My version info:

Ubuntu@0136-ict-prxmx50056:~/mistral.rs$ gcc --version
gcc (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0

Ubuntu@0136-ict-prxmx50056:~/mistral.rs$ nvcc --version
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0

=============

I used following steps:

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

sudo apt install libssl-dev
sudo apt install pkg-config

git clone https://github.com/EricLBuehler/mistral.rs.git
cd mistral.rs

cargo build --release --features cuda    => This is where it errors out. 

cp ./target/release/mistralrs-server ./mistralrs_server

./mistralrs_server -i plain -m microsoft/Phi-3-mini-128k-instruct -a phi3

Thanks.

**Comment by fahdmirza** [comment]
Hi,
 Could you please point me to the solution of this issue, if it already has been triaged? Thanks.

**Comment by fahdmirza** [comment]
Thanks @EricLBuehler . I am using Ubuntu 22.04

Ubuntu@0136-ict-prxmx50056:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

I wanted to review it for my channel at https://www.youtube.com/@fahdmirza

regards,

**Comment by EricLBuehler** [comment]
Hi @fahdmirza that seems super cool! Sorry for not getting back, I've been busy adding some new features!

Can you please try:
```
sudo apt-get install build-essential
sudo apt-get install g++
```

**Comment by fahdmirza** [comment]
All good, yes I have already tried that but same error. Thanks.

**Comment by EricLBuehler** [comment]
@fahdmirza I haven't been able to reproduce this. Perhaps it is caused by a specific environment issue? Please feel free to reopen.
