### ISSUE TITLE
Seems to be slower than original model.

### ISSUE THREAD

**Issue by 2U1** [EricLBuehler/mistral.rs#575]
It seems to be a bit slower than using the original phi3-vision model.
I even tried ISQ and its still slower.

The original takes about 5 to 6 seconds and, when using mistral.rs it takes about 9 to 11seconds. 

Is there something I'm missing?

**Comment by EricLBuehler** [comment]
Thanks for reporting this. Are you building for CUDA, Metal, or some CPU accelerator?

**Comment by 2U1** [comment]
@EricLBuehler I'm building for CUDA.

**Comment by EricLBuehler** [comment]
@2U1 can you please let me know the prompt and completion/decoding T/s metrics for the Python and mistral.rs implementations?

**Comment by EricLBuehler** [comment]
Just merged #580 which adds +20% T/s to prompt processing speed of Phi 3V (in the CLIP model).

**Comment by EricLBuehler** [comment]
@2U1 closing now as I am measuring a 24% throughput improvement over Transformers including image processing, prompt, and decoding steps.
