### ISSUE TITLE
Paged Attention NVCC compile issue

### ISSUE THREAD

**Issue by joshpopelka20** [EricLBuehler/mistral.rs#603]
**Describe the bug**
When running cargo run with latest code, I'm getting this issue with the paged attention code:

```
  = note: /usr/bin/ld: /home/ec2-user/mistral.rs/mistralrs-paged-attn/libpagedattention.a(pagedattention-b5087c446beb6afd.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: /home/ec2-user/mistral.rs/mistralrs-paged-attn/libpagedattention.a(reshape_and_cache_kernel-160d2c98493955ed.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
```

I tried updating the build.rs under `mistral.rs/mistralrs-paged-attn` with the NVCC flag code and passing fPIC flag, but still having an issue.

OS info:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

I'll continue troubleshooting, but I know that this has happened multiple times. 

**Latest commit**
5503887

**Comment by joshpopelka20** [comment]
I got it to work. Needed to add the target_family to the CUDA_NVCC_FLAGS. Here is the PR: [https://github.com/EricLBuehler/mistral.rs/pull/604](https://github.com/EricLBuehler/mistral.rs/pull/604)

**Comment by EricLBuehler** [comment]
Ah great! I just merged #604.

**Comment by joshpopelka20** [comment]
Thanks! I did a clean clone and build. It worked without issue.

I have one concern:
```
2024-07-22T19:18:18.930302Z  INFO mistralrs_core::paged_attention: Allocating **17325 MB** for PagedAttention KV cache
2024-07-22T19:18:18.930315Z  INFO mistralrs_core::paged_attention: Using PagedAttention with block size 32 and 2772 GPU blocks: available context length is 88704 tokens
```

That paged attention allocates a lot of memory. I know you mentioned before that splitting the KV cache may not be possible, but have you heard of RingAttention (https://arxiv.org/abs/2310.01889)? I'm just not sure if it's possible without having a ring topology (like they mention in the paper). 

I've been trying to work on it, but it's taking me a lot of time. Let me know your thoughts and I'll try to devote more time to it. Also, I'd probably need some guidance on how to add it to the project.

**Comment by EricLBuehler** [comment]
> That paged attention allocates a lot of memory.

We provide 2 ways to control this: by setting the paged attention memory usage percentage (defaulting to 90%), or by setting an exact count in MBs. Perhaps you could try that?

> I know you mentioned before that splitting the KV cache may not be possible, but have you heard of RingAttention (https://arxiv.org/abs/2310.01889)? I'm just not sure if it's possible without having a ring topology (like they mention in the paper).

That seems super interesting! I'll take a look at it.

> I've been trying to work on it, but it's taking me a lot of time. Let me know your thoughts and I'll try to devote more time to it. Also, I'd probably need some guidance on how to add it to the project.

I think this would be an amazing addition - It would be a great strategy to have for users with multiple GPUs! To make it easier adding RingAttention to this project, I would recommend that you add it to one model at first, create the PR, and then we can work on abstracting it out.

Please feel free to reach out to me directly if you would like if you have any questions, either here (if you create a tracking issue), or via DM from the Discord.

**Comment by joshpopelka20** [comment]
Great! Let me add a new issue to track it and I'll close this one.
