### ISSUE TITLE
Serving available models via http://0.0.0.0:1234/models

### ISSUE THREAD

**Issue by ChristianWeyer** [EricLBuehler/mistral.rs#620]
Can we have a /models endpoint which lists all available models (at runtime)?
Tools like OpenWeb UI use this to integrate their great UI with different backends.

Thanks!

**Comment by EricLBuehler** [comment]
@ChristianWeyer we have such an API: https://github.com/EricLBuehler/mistral.rs/blob/master/examples/http.md#get-v1models

**Comment by ChristianWeyer** [comment]
Perfect, thanks :-)
