### ISSUE TITLE
[feat] running the server from rust 

### ISSUE THREAD

**Issue by louis030195** [EricLBuehler/mistral.rs#627]
i'm looking for some production ready LLM API that I can use from rust as a lib in https://github.com/louis030195/screen-pipe

would it be possible to provide some abstraction like

```rs
let api = mistral_rs::api::new("phi42").load()
api.serve()
// openai style api ... function calling available if possible
```

i also use axum 

atm implementing the api myself with candle

**Comment by EricLBuehler** [comment]
Hey @louis030195! Currently, we don't exactly provide an API for launching the server from Rust, but you can look at [`mistralrs-server/main.rs`](https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-server/src/main.rs) and[`mistralrs-server/chat_completion.rs`](https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-server/src/chat_completion.rs) for inspiration. If this is critical, I can add it though!

I would take a look at the `setup()` functions is all the Rust examples. For instance, [this one](https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs/examples/simple/main.rs#L24-L55). Our loading API provides a very high level of control to you, the user. To make such a clean API as you suggest above, you would need to set a bunch of defaults, but this should be possible. I'm happy to help!

The user-facing API of mistral.rs revolves around the `MistralRs` struct, so you can use that as state in axum as we do, and send requests to it.

**Comment by ericcarmi** [comment]
I got an example working with a rust server, though it is just using a simple TCP port, might be a good enough example for others to build from. 

https://github.com/ericcarmi/local-llm

**Comment by louis030195** [comment]
my dream would be to be able to plug to https://github.com/vercel/ai directly the api from the client 

```ts
const {messages} = useChat({api: "http://localhost:12345/api"})
// ...
```
