### ISSUE TITLE
Function / Tools Calling in OpenAI API-compatible server

### ISSUE THREAD

**Issue by ChristianWeyer** [EricLBuehler/mistral.rs#628]
For fully integrating with OpenAI API-based solutions, we need the server to support function / tools calling:
https://platform.openai.com/docs/guides/function-calling
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

**Comment by EricLBuehler** [comment]
Hi @ChristianWeyer!

This is a critical feature, I will definitely add it.

**Comment by EricLBuehler** [comment]
@ChristianWeyer see #649! About to merge 😉!

**Comment by ChristianWeyer** [comment]
Yihaaaaaa!!! Thanks, man!

**Comment by EricLBuehler** [comment]
@ChristianWeyer just merged it!

https://github.com/EricLBuehler/mistral.rs/blob/master/docs/TOOL_CALLING.md
