### ISSUE TITLE
Add DRY repetition penalty

### ISSUE THREAD

**Issue by p-e-w** [EricLBuehler/mistral.rs#635]
DRY is a modern repetition penalty that is superior to the standard frequency and presence penalties at preventing repetition, while having virtually none of their negative effects on language quality.

Original implementation with detailed explanation: https://github.com/oobabooga/text-generation-webui/pull/5677

C++ implementation in llama.cpp (pending merge): https://github.com/ggerganov/llama.cpp/pull/6839

Independent C++ implementation in Kobold (merged): https://github.com/LostRuins/koboldcpp/pull/982

**Comment by EricLBuehler** [comment]
@p-e-w I just added a PR for this. If you could give it a review that would be amazing.
