### ISSUE TITLE
Matrix/Element Chatroom

### ISSUE THREAD

**Issue by oldgithubman** [EricLBuehler/mistral.rs#639]
Emphasis on *humbly*. I don't expect this will change, but I'd like to give voice to those (myself included) who refuse to/can't use discord. It sucks that so much of the open-source community use it for their primary means of communication, effectively locking people like myself out of the conversation. It's even worse when projects use it as the sole means of support, or, worse still, documentation.

Again, I don't *expect* this to change, but as a possible alternative, I'd like to suggest matrix/element. I'm pretty sure it even has the ability to "bridge" its rooms with discord, which would allow the discord server to remain as-is

**Comment by EricLBuehler** [comment]
Hi @oldgithubman! Thank you for your input. I just added a Matrix chatroom: https://matrix.to/#/#mistral.rs:matrix.org.

I'm curious on how to bridge the rooms with discord, do you know how to do this?

**Comment by EricLBuehler** [comment]
I think it would be best to keep Matrix/Discord seperate for now, thanks for the links!
