### ISSUE TITLE
API Docs 404

### ISSUE THREAD

**Issue by oldgithubman** [EricLBuehler/mistral.rs#646]
## Describe the bug
On the main readme, the "API Docs" link https://github.com/EricLBuehler/mistral.rs/blob/master/examples/http.md 404's.

Edit - the following link, "Running" "https://github.com/EricLBuehler/mistral.rs/blob/master/README.md#run doesn't appear to work either (it just links back to the main readme and doesn't seem to jump to anything)

**Comment by EricLBuehler** [comment]
This should be fixed in #648!
