### ISSUE TITLE
note: LINK : fatal error LNK1181: cannot open input file 'mistralcuda.lib'

### ISSUE THREAD

**Issue by ricesin888** [EricLBuehler/mistral.rs#653]
- Operating system (Windows)
 nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:42:34_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0

cargo build --release --features cuda

error message: 
  = note: LINK : fatal error LNK1181: cannot open input file 'mistralcuda.lib'

error: could not compile `mistralrs-server` (bin "mistralrs-server") due to 1 previous error

**Comment by EricLBuehler** [comment]
Hey @ricesin888! Are you compiling via a Visual Studio installed compiler? If so, can you please update Visual Studio?

**Comment by ricesin888** [comment]
update cuda version to 12.5, fixed !

**Comment by EricLBuehler** [comment]
Great!
