### ISSUE TITLE
How's the M1 performance compare with llama.cpp or ollama?

### ISSUE THREAD

**Issue by luohao123** [EricLBuehler/mistral.rs#673]
How's the M1 performance compare with llama.cpp or ollama?

**Comment by leoromanovsky** [comment]
Have you considered benchmarking it yourself?

**Comment by lucgagan** [comment]
I am also curious to know

**Comment by EricLBuehler** [comment]
@luohao123 @lucgagan @leoromanovsky very similar, see #903!
