### ISSUE TITLE
windows build error note: LINK : fatal error LNK1181: cannot open input file 'mistralgptq.lib'

### ISSUE THREAD

**Issue by openmynet** [EricLBuehler/mistral.rs#712]
```powershell
$vsPath="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
Import-Module ("$vsPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
Enter-VsDevShell -VsInstallPath "$vsPath"  -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64"

$env:CUDA_PATH="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5"
$env:CUDA_ROOT="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5"
$env:CUDA_TOOLKIT_ROOT_DIR="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5"

cargo build --release --features cuda
```
## Error

>
error message:
= note: LINK : fatal error LNK1181: cannot open input file 'mistralgptq.lib'
could not compile `mistralrs-bench` (bin "mistralrs-bench") due to 1 previous error

error message:
= note: LINK : fatal error LNK1181: cannot open input file 'mistralgptq.lib'
could not compile `mistralrs-server` (bin "mistralrs-server") due to 1 previous error

## OS
Windows10 22H2 - 19045.4780
Microsoft Visual Studio\2022\BuildTools:  ver. 17.11.1

# nvcc --version
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0
```
# nvidia-smi
```
Sat Aug 24 18:30:12 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070      WDDM  |   00000000:07:00.0  On |                  N/A |
|  0%   56C    P8             12W /  185W |    1628MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

```

build commit: 60479fb7e9bae5f90276acca2e7d9f019f923f46

**Comment by misureaudio** [comment]
Same problem here. I managed to compile with  CUDA til the 0.2.24.

From 0.2.25 : fatal error LNK1181 cannot open input file mistralgptq.lib

I can find just a libmistralgptq.a in "C:\Users\MATTIA\Desktop\rustsrc\mistral.rs\target\release\build\mistralrs-quant-082fa716d3f4791e\out"

**Comment by misureaudio** [comment]
// let out_file = build_dir.join("libmistralgptq.a"); <--- original, not working
    let out_file = build_dir.join("mistralgptq.lib"); ---> modified, build + install ok

line 38, build.rs in mistral.rs\mistral-quant directory

**Comment by EricLBuehler** [comment]
Hi @openmynet @misureaudio! I think this should be fixed in #729, can you please confirm that it builds now?

**Comment by misureaudio** [comment]
Thank You @EricLBuehler , I was able to build and install with no problem with the modified code

**Comment by EricLBuehler** [comment]
@misureaudio thanks you for confirming!

@openmynet I just emrged #729 into `master`, so after `git pull`, it should work on windows.
