### ISSUE TITLE
"Missing field `lm_head_bias` at line 138 column 1" during the the installation process

### ISSUE THREAD

**Issue by Antix5** [EricLBuehler/mistral.rs#768]
## Describe the bug
When installing Phi 3.5 MoE, I encounter the following error `Error: missing field `lm_head_bias` at line 138 column 1` after downloading the weights 
(That was on Metal on MacOS Sequoia)

Here is the installation command I ran :
./target/release/mistralrs-server --isq Q4_0 -i plain -m microsoft/Phi-3.5-mini-instruct -a phi3.5moe
(work when using phi3 at the end instead)
## Latest commit or version
Which commit or version you ran with.
[1cdec83](https://github.com/EricLBuehler/mistral.rs/commit/1cdec83092b4eccf2852bcf659123a150c340b25)

**Comment by EricLBuehler** [comment]
@Antix5 it seems you're selecting the phi3.5moe architecture, which is for the Phi 3.5 MoE model. However, according to your command, you are loading the Phi 3.5 (non MoE) model.

The following commands should work:

./target/release/mistralrs-server --isq Q4_0 -i plain -m microsoft/Phi-3.5-mini-instruct -a phi3

./target/release/mistralrs-server --isq Q4_0 -i plain -m  microsoft/Phi-3.5-MoE-instruct-a phi3.5moe

**Comment by Antix5** [comment]
Oh, oops, sorry for bothering you. I copied the command and modified it, but I didn’t notice I forgot to change that part. Sorry for the trouble. Thank you, and I hope this issue helps others avoid making the same silly mistake as me
