### ISSUE TITLE
RequestMessage with tool_calls in Assistant message.

### ISSUE THREAD

**Issue by Jeadie** [EricLBuehler/mistral.rs#793]
## Describe the bug
- To follow OpenAI spec (and what other open source models, e.g. llama3.1), expect for Assistant messages with tool calls, messages should look like this
```json
  "messages": [
    {
      "role": "assistant",
      "content": "",
     "tool_calls": [
        {
          "id": "call-243240c8",
          "type": "function",
          "function": {
            "name": "current_weather",
            "arguments": "{\"county\": \"somewhere\"}"
          }
        }
      ]
    }
]
```

In mistral.rs, we JSON string the full `"tool_calls"` value, e.g. https://github.com/EricLBuehler/mistral.rs/blob/b6b722e34ecff2d5cf4fccb57220384db386a932/mistralrs/examples/lower_level/tools/main.rs#L127-L139

In fact, [MessageContent](https://github.com/EricLBuehler/mistral.rs/blob/b6b722e34ecff2d5cf4fccb57220384db386a932/mistralrs-core/src/request.rs#L31) only supports String values. 

This restricts the ability to feed the result of tool calls back to various models 

Also value should be `"arguments"` and not `"parameters"` (parameters is used in JSONSchema for `tools` key.

**Comment by Jeadie** [comment]
The issue is that certain common open-source Jinja `chat_templates` expect a non-serialised JSON object for `tool_calls` fields when converting `RequestMessages` to an unstructured string.

For example [`meta-llama/Llama-3.1-8B-Instruct`](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct) has a [chat_template](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/blob/main/tokenizer_config.json#L2053), with the following 
```jinja
{%- if not message.tool_calls|length == 1 %}
    {{- raise_exception(\"This model only supports single tool-calls at once!\") }}
{%- endif %}
```
This is not checking the length of the JSON string is 1, but rather that the JSON array has one entry.

**Comment by Jeadie** [comment]
Initial comments were incorrect, the [example](https://github.com/EricLBuehler/mistral.rs/issues/793#issuecomment-2373530131) needs to be.
```rust
tool_calls = 

messages.push(IndexMap::from([ 
     ("role".to_string(), Either::Left("asistant".to_string())), 
     ("content".to_string(), Either::Left("".to_string())), 
     ( 
         "tool_calls".to_string(), 
         Either::Right(Vec![
             IndexMap::from([ 
                 ("Id".to_string(), tool_call.id),
                 ("function".to_string(), json!({ 
                     "name": called.function.name, 
                     "arguments": called.function.arguments, 
                 }),
                 ("type".to_string(), "function".to_string()"),
                 
             ])
        ])
     ), 
 ]));
 ```
 
This resolves the issue mentioned [above](https://github.com/EricLBuehler/mistral.rs/issues/793#issuecomment-2381898260). 

However, this still does not resolve all issues found in trying to use the `chat_template` from [meta-llama/Llama-3.1-8B-Instruct](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct). The next
```jinja
{{- '<|start_header_id|>assistant<|end_header_id|>\n\n' -}}
{{- '{"name": "' + tool_call.name + '", ' }}
{{- '"parameters": ' }}
{{- tool_call.arguments | tojson }}
{{- "}" }}
```

**Comment by Jeadie** [comment]
The impact of this issue is that `mistral.rs` can call tools, but cannot take the result of tools as inputs.

**Comment by EricLBuehler** [comment]
Closing as this has been implemented.
