### ISSUE TITLE
Can't read image file path with space on MacOS

### ISSUE THREAD

**Issue by chigkim** [EricLBuehler/mistral.rs#827]
## Describe the bug
Mistral-server in interactive mode cannot read the image file path with space.
I tried with `/file path`, `"/file path"`, `/file\ path`, and none of them worked.
When If I renamed the path without spaces, it worked.

## Latest commit or version
3e79d85

**Comment by EricLBuehler** [comment]
@chigkim thanks for reporting. Will add a fix.

**Comment by elleparker** [comment]
can you fix me plz?
