### ISSUE TITLE
support qwen2 gguf architecture

### ISSUE THREAD

**Issue by franklucky001** [EricLBuehler/mistral.rs#851]
# run docker 
```bash
docker run --name mistral \
	-v /home/gxy/modelscope/Qwen2.5-1.5B-Instruct-GGUF:/model \
	-p 8888:80 \
	-e RUST_BACKTRACE=1 \
	-t ericlbuehler/mistral.rs:cpu-latest \
	-i gguf -m /model -f qwen2.5-1.5b-instruct-q4_k_m.gguf

```
# run error
> called `Result::unwrap()` on an `Err` value: Unknown GGUF architecture `qwen2`

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: mistralrs_core::gguf::GGUFArchitecture::from_value
   2: mistralrs_core::gguf::content::Content<R>::from_readers
   3: <mistralrs_core::pipeline::gguf::GGUFLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_path
   4: <mistralrs_core::pipeline::gguf::GGUFLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_hf
   5: mistralrs_server::main::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: mistralrs_server::main
   8: std::sys::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal
  11: main
  12: <unknown>
  13: __libc_start_main
  14: _start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: mistralrs_core::gguf::content::Content<R>::from_readers
   4: <mistralrs_core::pipeline::gguf::GGUFLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_path
   5: <mistralrs_core::pipeline::gguf::GGUFLoader as mistralrs_core::pipeline::loaders::Loader>::load_model_from_hf
   6: mistralrs_server::main::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: mistralrs_server::main

**Comment by EricLBuehler** [comment]
@franklucky001 #860 supports GGUF Qwen 2!

**Comment by franklucky001** [comment]
@EricLBuehler Qwen2 define in master branch 
```rust
pub enum GGUFArchitecture {
    Llama,
    Mpt,
    Gptneox,
    Gptj,
    Gpt2,
    Bloom,
    Falcon,
    Mamba,
    Rwkv,
    Phi2,
    Phi3,
    Starcoder2,
    Qwen2,
}

```
but not found in 0.3.1 https://github.com/EricLBuehler/mistral.rs/blob/v0.3.1/mistralrs-core/src/gguf/mod.rs
```rust
pub enum GGUFArchitecture {
    Llama,
    Mpt,
    Gptneox,
    Gptj,
    Gpt2,
    Bloom,
    Falcon,
    Mamba,
    Rwkv,
    Phi2,
    Phi3,
    Starcoder2,
}
```
Can you provide the docker image built from the master branch?

**Comment by franklucky001** [comment]
@EricLBuehler that's great! thanks
