### ISSUE TITLE
Vision interactive mode for gguf models

### ISSUE THREAD

**Issue by ShaheerANative** [EricLBuehler/mistral.rs#882]
Hi,

I am trying to load a Phi-3.5-3.8B-vision-instruct-Q8_0 GGUF model using the command for loading local GGUF file:

./mistralrs-server -i gguf  --quantized-model-id path/to/files --quantized-filename path/to/model.gguf

^^ This command works fine for loading text-only interactive mode but adding vision-plain after the -i flag does not work to start image -based interactive mode. 

Would be very useful to test GGUF vision models in this way, and could not find existing method to do so. Thanks.

**Comment by DenisBobrovskiy** [comment]
I am also trying to load a Phi-3.5 vision model through a gguf file, would appreciate any guidance on this, thanks!

**Comment by EricLBuehler** [comment]
@DenisBobrovskiy @ShaheerANative this is a tough problem because llama.cpp does not support vision models, and we don't want to support anything nonstandard, so you would need to use a UQFF (https://huggingface.co/collections/EricB/uqff-670e4a49d56ecdd3f7f0fd4c) model or ISQ
