### ISSUE TITLE
Failed to parse Cargo.toml: [workspace] missing field `package`

### ISSUE THREAD

**Issue by helix84** [EricLBuehler/mistral.rs#883]
## Minimum reproducible example
Following https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-pyo3/README.md

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env

mkdir -p ~/venv/mistralrs/
cd ~/venv/mistralrs/ && python3 -m pipenv shell

pip install mistralrs -v
...
Successfully installed mistralrs-mkl-0.3.1

## Error
````
maturin develop -r --features mkl
💥 maturin failed
  Caused by: Failed to parse Cargo.toml at /home/user/venv/mistralrs/mistral.rs/Cargo.toml
  Caused by: TOML parse error at line 1, column 1
  |
1 | [workspace]
  | ^
missing field `package`
````

## Other information
Please specify:
- Debian 11
- tried both no accel and MKL
- cargo --version
cargo 1.82.0 (8f40fc59f 2024-08-21)
- python --version
Python 3.9.2
- same with latest python via uv: python --version
Python 3.13.0

## Latest commit or version
latest (76c1f4ed46956262e243a02334c5dec9534d9aeb)

**Comment by EricLBuehler** [comment]
Hi @helix84! This should work if you build in the `mistralrs-pyo3` directory.
