### ISSUE TITLE
0.3.2 #891 build failure on Windows 11

### ISSUE THREAD

**Issue by misureaudio** [EricLBuehler/mistral.rs#896]
## Minimum reproducible example
cargo build --release --features cuda

## Error
   Compiling windows-core v0.52.0
error[E0063]: missing field `seed_value` in initializer of `cuda_backend::device::CudaDevice`
   --> C:\Users\MATTIA\.cargo\git\checkouts\candle-c6a149c3b35a488f\629ec72\candle-core\src\cuda_backend\device.rs:203:12
    |
203 |         Ok(Self {
    |            ^^^^ missing `seed_value`

   Compiling csv-core v0.1.11
   Compiling base64 v0.13.1
   Compiling arrayvec v0.7.6
   Compiling allocator-api2 v0.2.18
   Compiling indenter v0.3.3
   Compiling overload v0.1.1
   Compiling macro_rules_attribute-proc_macro v0.2.0
For more information about this error, try `rustc --explain E0063`.
error: could not compile `candle-core` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish... 

## Other information
Windows 11

C:\Users\MATTIA>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:26:51_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0

C:\Users\MATTIA>nvidia-smi
Tue Oct 29 09:24:23 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+=============|
|   0  NVIDIA RTX A2000             WDDM  |   00000000:21:00.0  On |                    0 |
| 30%   32C    P8              7W /   70W |     391MiB /   5754MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
## Latest commit or version
0.3.2 #891

**Comment by misureaudio** [comment]
Possible remedy:

Correction, proposed:

impl CudaDevice {
    pub fn new_with_stream(ordinal: usize) -> Result<Self> {
        let device = cudarc::driver::CudaDevice::new_with_stream(ordinal).w()?;
        let blas = cudarc::cublas::CudaBlas::new(device.clone()).w()?;
        let curand = cudarc::curand::CudaRng::new(299792458, device.clone()).w()?;
        Ok(Self {
            id: DeviceId::new(),
            device,
            blas: Arc::new(blas),
            curand: Arc::new(Mutex::new(CudaRng(curand))),
----->      seed_value: Arc::new(RwLock::new(299792458)),
        })
    }
}

It builds, after copying the absent seed_value from the following rust code, Ok(Self...

**Comment by misureaudio** [comment]
Please verify if the proposed correction is appropriate, not limited to the fact that it allows to complete the build process.

Thank You!

**Comment by EricLBuehler** [comment]
@misureaudio this should be fixed now, I just pushed a fix. Can you please confirm?

**Comment by misureaudio** [comment]
> @misureaudio this should be fixed now, I just pushed a fix. Can you please confirm?

Confirmed.

Build & install OK.

Thank You!

**Comment by wingrunr21** [comment]
@EricLBuehler this also caused the `v0.3.2` [docker cuda build to fail](https://github.com/EricLBuehler/mistral.rs/actions/runs/11557575711).

**Comment by EricLBuehler** [comment]
@wingrunr21 thanks. Will be taking a look to fix this in the upcoming v0.3.3.

**Comment by EricLBuehler** [comment]
@misureaudio  this should be fixed now, please feel free to reopen.

**Comment by misureaudio** [comment]
@EricLBuehler 

build phase ok for v 0.3.4 #966
However, Install phase exits with the following error:

   Compiling tower-http v0.5.2
error[E0308]: mismatched types
   --> mistralrs-core\src\pipeline\llg.rs:15:67
    |
15  |     let bt = toktrie_hf_tokenizers::ByteTokenizer::from_tokenizer(tokenizer)
    |              ---------------------------------------------------- ^^^^^^^^^ expected `Tokenizer`, found `tokenizers::Tokenizer`
    |              |
    |              arguments to this function are incorrect
    |
    = note: `tokenizers::Tokenizer` and `Tokenizer` have similar names, but are actually distinct types
note: `tokenizers::Tokenizer` is defined in crate `tokenizers`
   --> C:\Users\MATTIA\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokenizers-0.20.4\src\tokenizer\mod.rs:408:1
    |
408 | pub struct Tokenizer(
    | ^^^^^^^^^^^^^^^^^^^^
note: `Tokenizer` is defined in crate `tokenizers`
   --> C:\Users\MATTIA\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokenizers-0.21.0\src\tokenizer\mod.rs:408:1
    |
408 | pub struct Tokenizer(
    | ^^^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `tokenizers` are being used?
note: associated function defined here
   --> C:\Users\MATTIA\.cargo\git\checkouts\llguidance-fc2ad2787f3486eb\cfef3df\toktrie_hf_tokenizers\src\lib.rs:72:12
    |
72  |     pub fn from_tokenizer(mut hft: Tokenizer) -> Result<ByteTokenizer> {
    |            ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mistralrs-core` (lib) due to 1 previous error
