### ISSUE TITLE
Mistral.rs server build error

### ISSUE THREAD

**Issue by grpathak22** [EricLBuehler/mistral.rs#915]
## Minimum reproducible example
The minium example to reproduce the error. Simpler examples make it easier and faster to fix!
cargo build --release --features cuda --workspace --exclude mistralrs-pyo3
## Error
What is the error? If the error is very long, please try to extract an excerpt of it and post a link to a [Gist](https://gist.github.com/)

  Compiling data-url v0.3.1
error[E0308]: `?` operator has incompatible types
   --> mistralrs-core/src/paged_attention/layers/paged_attention.rs:102:45
    |
102 |                 let att = att.broadcast_add(mask.unsqueeze(0)?.unsqueeze(0)?)?;
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&Tensor`, found `Tensor`
    |
    = note: `?` operator cannot convert from `candle_core::Tensor` to `&candle_core::Tensor`
help: consider borrowing here
    |
102 |                 let att = att.broadcast_add(&mask.unsqueeze(0)?.unsqueeze(0)?)?;
    |                                             +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mistralrs-core` (lib) due to 1 previous error

## Other information
Please specify:
- Operating system (Windows, MacOS, WSL2, Linux, etc):Linux
- GPU or accelerator information
    - If CUDA, please run `nvcc --version`, `nvidia-smi`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
## Latest commit or version
Latest

**Comment by EricLBuehler** [comment]
@grpathak22 thank you for reporting this. This is now fixed on my machine.

**Comment by grpathak22** [comment]
Great!
