### ISSUE TITLE
Status code of HTTP error messages is not 4xx or 5xx

### ISSUE THREAD

**Issue by lucasavila00** [EricLBuehler/mistral.rs#97]
I can fix that. It's similar to https://github.com/EricLBuehler/mistral.rs/pull/80

Here: https://github.com/EricLBuehler/mistral.rs/blob/master/mistralrs-server/src/main.rs#L140

`e.to_string().into_response()` does not carry the information that string is of an error, thus we get wrong HTTP status code

In the end this makes the OpenAI client return an unhelpful message:

```
Traceback (most recent call last):
  File "/home/lucas/oss/mistral.rs/examples/server/chat.py", line 25, in <module>
    resp = completion.choices[0].message.content
AttributeError: 'str' object has no attribute 'choices'
```

**Comment by EricLBuehler** [comment]
Thanks for raising this! If you can submit a PR that would be great.
