### ISSUE TITLE
error[E0599]: no method named `is_none_or` found for enum `std::option::Option` in the current scope

### ISSUE THREAD

**Issue by Dead-Bytes** [EricLBuehler/mistral.rs#995]
## Minimum reproducible example
i have cloned the repo and then using cargo build --release

## Error
error[E0599]: no method named `is_none_or` found for enum `std::option::Option` in the current scope
   --> mistralrs-core/src/pipeline/amoe.rs:522:18
    |
520 |               if path
    |  ________________-
521 | |                 .extension()
522 | |                 .is_none_or(|e| e.to_string_lossy() != *"csv")
    | |_________________-^^^^^^^^^^
    |
help: there is a method `is_none` with a similar name, but with different arguments
   --> /build/rustc-1.80-R0vcdR/rustc-1.80-1.80.1+dfsg0ubuntu1/library/core/src/option.rs:653:5

error[E0599]: no method named `is_none_or` found for enum `std::option::Option` in the current scope
   --> mistralrs-core/src/pipeline/isq.rs:310:43
    |
310 | ...   if serialized.extension().is_none_or(|ext| ext != "uqff") {
    |                                 ^^^^^^^^^^
    |
help: there is a method `is_none` with a similar name, but with different arguments
   --> /build/rustc-1.80-R0vcdR/rustc-1.80-1.80.1+dfsg0ubuntu1/library/core/src/option.rs:653:5

## Other information
Please specify:
- Operating system : Ubuntu 24.10

## Latest commit or version
commit version :  68c078f

**Comment by EricLBuehler** [comment]
Hi @Dead-Bytes! From the traceback, it appears your Rust version is 1.80. `is_none_or` was added in Rust 1.82, can you please update your Rust version and check if this fixes it?

**Comment by Dead-Bytes** [comment]
ohk sure, thanks

**Comment by Dead-Bytes** [comment]
yes it solved the issue thanks
